### PR TITLE
Remove libcurl4 in scripts/setup/setup_ubuntu.sh && add Dockerfile support for dockerhub autobuild

### LINKED ISSUE #72: make error
https://github.com/pkumod/gStore/blob/4bd610cd192a7c3c58836d8d6dc11f4f08f4e041/scripts/setup/setup_ubuntu.sh#L23

there's no package naming libcurl4, which causes `libcurl4-openssl-dev` installation ignored. and `make` failed with `cannot find -lcurl`.

### LINKED ISSUE #75: dockefile is incomplete to build from bare machine
the origin dockerfile needs user run `make pre` on the host, according to the [directions on docker build from source](https://github.com/pkumod/gStore/blame/master/docs/DOCKER_DEPLOY_CN.md#L19), which violates the docker's principle.
it's better to do all the dirty job inside build container and reduce the image size if possible.
the base image should also be uniformed for global use.

### PR DESCRIPTION
**Pull request by yzs981130**
fix #72 
fix #75

### CODE REVIEW

**Comment by bookug** [comment]
@WenJieLiHnu

**Comment by bookug** [comment]
@suxunbin

**Comment by SoftlySpoken** [comment]
Hi,
The error in the Ubuntu setup script will indeed cause problems. Your modification will be merged into master.
However, as we are planning to come up with a new Docker mirror in the near future (admittedly, the current Dockerfile hasn’t been maintained as well as it should), your modifications of it will be pending until then. We will definitely consider them when the time comes.
If such treatment is acceptable to you, I will merge your pull request like so as soon as possible.
Thank you for your contributions!

**Comment by SoftlySpoken** [comment]
Hi,
We have updated the Dockerfile in the current main branch (0.9), and your modifications have been included.

**Pull request closed without merging**
